# Generated by Django 3.1.8 on 2021-10-10 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigIntegerField()),
                ('full_url', models.TextField(blank=True)),
                ('short_url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
